/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as FavouriteTracksRouteRouteImport } from './routes/favourite-tracks/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistAllRouteRouteImport } from './routes/playlist/all/route'
import { Route as PlaylistPlaylistIdRouteRouteImport } from './routes/playlist/$playlistId/route'
import { Route as ArtistAllRouteRouteImport } from './routes/artist/all/route'
import { Route as ArtistArtistRouteRouteImport } from './routes/artist/$artist/route'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouriteTracksRouteRoute = FavouriteTracksRouteRouteImport.update({
  id: '/favourite-tracks',
  path: '/favourite-tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistAllRouteRoute = PlaylistAllRouteRouteImport.update({
  id: '/playlist/all',
  path: '/playlist/all',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistIdRouteRoute = PlaylistPlaylistIdRouteRouteImport.update({
  id: '/playlist/$playlistId',
  path: '/playlist/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistAllRouteRoute = ArtistAllRouteRouteImport.update({
  id: '/artist/all',
  path: '/artist/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistArtistRouteRoute = ArtistArtistRouteRouteImport.update({
  id: '/artist/$artist',
  path: '/artist/$artist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favourite-tracks': typeof FavouriteTracksRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/artist/$artist': typeof ArtistArtistRouteRoute
  '/artist/all': typeof ArtistAllRouteRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRouteRoute
  '/playlist/all': typeof PlaylistAllRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favourite-tracks': typeof FavouriteTracksRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/artist/$artist': typeof ArtistArtistRouteRoute
  '/artist/all': typeof ArtistAllRouteRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRouteRoute
  '/playlist/all': typeof PlaylistAllRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favourite-tracks': typeof FavouriteTracksRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/artist/$artist': typeof ArtistArtistRouteRoute
  '/artist/all': typeof ArtistAllRouteRoute
  '/playlist/$playlistId': typeof PlaylistPlaylistIdRouteRoute
  '/playlist/all': typeof PlaylistAllRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favourite-tracks'
    | '/settings'
    | '/artist/$artist'
    | '/artist/all'
    | '/playlist/$playlistId'
    | '/playlist/all'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favourite-tracks'
    | '/settings'
    | '/artist/$artist'
    | '/artist/all'
    | '/playlist/$playlistId'
    | '/playlist/all'
  id:
    | '__root__'
    | '/'
    | '/favourite-tracks'
    | '/settings'
    | '/artist/$artist'
    | '/artist/all'
    | '/playlist/$playlistId'
    | '/playlist/all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavouriteTracksRouteRoute: typeof FavouriteTracksRouteRoute
  SettingsRouteRoute: typeof SettingsRouteRoute
  ArtistArtistRouteRoute: typeof ArtistArtistRouteRoute
  ArtistAllRouteRoute: typeof ArtistAllRouteRoute
  PlaylistPlaylistIdRouteRoute: typeof PlaylistPlaylistIdRouteRoute
  PlaylistAllRouteRoute: typeof PlaylistAllRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourite-tracks': {
      id: '/favourite-tracks'
      path: '/favourite-tracks'
      fullPath: '/favourite-tracks'
      preLoaderRoute: typeof FavouriteTracksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/all': {
      id: '/playlist/all'
      path: '/playlist/all'
      fullPath: '/playlist/all'
      preLoaderRoute: typeof PlaylistAllRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistId': {
      id: '/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof PlaylistPlaylistIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/all': {
      id: '/artist/all'
      path: '/artist/all'
      fullPath: '/artist/all'
      preLoaderRoute: typeof ArtistAllRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$artist': {
      id: '/artist/$artist'
      path: '/artist/$artist'
      fullPath: '/artist/$artist'
      preLoaderRoute: typeof ArtistArtistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavouriteTracksRouteRoute: FavouriteTracksRouteRoute,
  SettingsRouteRoute: SettingsRouteRoute,
  ArtistArtistRouteRoute: ArtistArtistRouteRoute,
  ArtistAllRouteRoute: ArtistAllRouteRoute,
  PlaylistPlaylistIdRouteRoute: PlaylistPlaylistIdRouteRoute,
  PlaylistAllRouteRoute: PlaylistAllRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
